stages:
  preprocess_data:
    cmd: python pipeline/preprocessing.py
    deps:
      - pipeline/preprocessing.py
      - data/raw/telecom_customer_churn.csv
    outs:
      - data/processed/telecom_customer_churn.csv
