stages:
  preprocess_data:
    cmd: python pipeline/preprocessing.py
    deps:
      - pipeline/preprocessing.py
      - data/raw/customer_churn.csv
    outs:
      - data/processed/processed_churn.csv
