# Model training parameters
data_loading:
  test_size: 0.20

model_building:
  experiment_name: experiment-1
  n_estimators: 22
  random_state: 42
  param_grid:
    criterion: ["gini", "entropy"]
    max_leaf_nodes: [5, 10, 15, 20]
